### ISSUE TITLE
Sorry, I'm newbie...

### ISSUE THREAD

**Issue by denisvolin** [ichinaski/pxl#11]
Hey!
Sorry, for using issues to ask, but I'm a total newbie in all that github stuff. 

The thing is that I used code of your pxl and I left bsd license text and your name as required to be used as [gocui](https://github.com/jroimartin/gocui/).Manager, rather than using underlying [termbox-go](https://github.com/nsf/termbox-go) directly.

So the question should I do anything else, except your name being present in the license text?
And I sorry again for probably foolish question and a definitely improper usage of issue filing.

**Comment by ichinaski** [comment]
Apologies @denisvolin, this issue totally skipped my mind!

You should not do anything else, I think is good as you describe. Again, sorry for the late response!
