### ISSUE TITLE
Does not display image in iTerm2 build 2.9.20160523

### ISSUE THREAD

**Issue by themartorana** [ichinaski/pxl#2]
Works fantastically in Terminal, but displays a black screen in iTerm2.

**Comment by themartorana** [comment]
Tested in both build 2.9.20160523, and 3.0.0 beta with the same results.

**Comment by ichinaski** [comment]
Good catch! 

Apparently iTerm does not report the terminal size in pixels, which makes it impossible to determine the cursor aspect ratio.

I will add a default aspect ratio, unless I find a more elegant workaround.

**Comment by ichinaski** [comment]
Fixed on d1429cbdc
