### ISSUE TITLE
Unable to Show Images Properly..

### ISSUE THREAD

**Issue by Xemin0** [ichinaski/pxl#24]
My environment:
```
XQuartz 2.8.5(X11)  with 256 colors enabled 
go1.19.5 darwin/amd64
```
To install pxl, I used 
```
go install github.com/ichinaski/pxl@latest
```
pxl was also added to my path, so I'm able to use 
```
pxl example.png
```
but every image, including the Examples from the project page, is not showing properly in the terminal.
At first I saw scrolling color lines/bars rolling upwards as if it's doing a vertical scan, then a few seconds later, what was shown in the terminal is only a small tiny bit of the original image (maybe tens of pixels I suppose )

i.g.  the [gh.png](https://raw.githubusercontent.com/ichinaski/pxl/master/img/gh.png) from the project page is showing just a white screen in my xterm.

**Comment by bieli** [comment]
@Xemin0 Maybe you need to set up Xterm in XQuartz to proper color interpretation mode like: `export TERM=xterm-256color`. On the Ubuntu 20.04.6 LTS desktop default gnome-terminal and Ubuntu server 20.04.6 LTS (external machine in the public cloud), everything was fine with pixels display on the terminal from images (both PNG and JPEG)!
